begin;
select plan(17);
insert into auth.users(id,email,raw_app_meta_data) values
  ('00000000-0000-4000-8000-000000006701','notes-admin@example.test','{}'),
  ('00000000-0000-4000-8000-000000006702','notes-seo@example.test','{}');
update public.profiles set role='admin' where id='00000000-0000-4000-8000-000000006701';
update public.profiles set role='seo_editor' where id='00000000-0000-4000-8000-000000006702';
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000006701',true);
set local role authenticated;
select is(public.save_redirect_with_admin_notes('/notes-test','/contact',true,true,'Private fixture note'),'/notes-test','admin saves a rule and note atomically');
select is((select notes from public.redirect_admin_notes where source_path='/notes-test'),'Private fixture note','admin reads the private note');
select throws_ok($$select public.save_redirect_with_admin_notes('/notes-test','/fees',true,true,repeat('x',1001))$$,'23514',null,'oversized note rejects the save');
select is((select destination_path from public.redirects where source_path='/notes-test'),'/contact','note failure rolls back the routing change');
select is((select notes from public.redirect_admin_notes where source_path='/notes-test'),'Private fixture note','note failure preserves its previous text');
select throws_ok($$select public.save_redirect_with_admin_notes('/notes-test','/notes-test',true,true,'Changed')$$,'23514',null,'loop validation remains active');
select throws_ok($$insert into public.redirect_admin_notes(source_path,notes) values('/notes-orphan','Orphan')$$,'23503',null,'private notes require an existing redirect');
reset role;
set local role anon;
select is((select destination_path from public.redirects where source_path='/notes-test'),'/contact','public routing remains available');
select throws_ok('select * from public.redirect_admin_notes','42501',null,'anonymous readers cannot inspect notes');
select throws_ok($$select public.save_redirect_with_admin_notes('/notes-test','/fees',true,true,'Blocked')$$,'42501',null,'anonymous callers cannot save notes');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000006702',true);
set local role authenticated;
select is((select count(*)::int from public.redirect_admin_notes),0,'SEO editors cannot read private notes');
with changed as(update public.redirect_admin_notes set notes='Blocked' returning source_path) select is((select count(*)::int from changed),0,'SEO editors cannot update notes');
select throws_ok($$select public.save_redirect_with_admin_notes('/notes-test','/fees',true,true,'Blocked')$$,'42501',null,'SEO editors cannot save through the RPC');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000006701',true);
set local role authenticated;
select is(public.save_redirect_with_admin_notes('/notes-test','/contact',true,true,''),'/notes-test','blank note clears it explicitly');
select is((select count(*)::int from public.redirect_admin_notes where source_path='/notes-test'),0,'cleared note is removed');
select public.save_redirect_with_admin_notes('/notes-test','/contact',true,true,'To clean up');
delete from public.redirects where source_path='/notes-test';
select is((select count(*)::int from public.redirect_admin_notes where source_path='/notes-test'),0,'redirect deletion cascades its note');
select is((select count(*)::int from public.redirects where source_path='/notes-test'),0,'the redirect itself was deleted');
reset role;
select * from finish();
rollback;
